#!/usr/bin/env python3
"""
LiveKit Token Generator for Voice Chat

SECURITY WARNING: This script is for development/testing only.
In production, tokens should be generated by your backend server.

Usage:
    python generate_livekit_token.py

The script will read credentials from environment variables:
    LIVEKIT_API_KEY
    LIVEKIT_API_SECRET
    LIVEKIT_URL (optional, for display only)
"""

import os
import sys
from datetime import timedelta

try:
    from livekit import api
except ImportError:
    print("ERROR: livekit package not installed")
    print("\nInstall it with:")
    print("    pip install livekit")
    sys.exit(1)


def generate_token(
    api_key: str,
    api_secret: str,
    room_name: str = "farm-voice-assistant",
    identity: str = "farmer-user",
    name: str = "Farmer",
    valid_for_hours: int = 24
) -> str:
    """
    Generate a LiveKit access token
    
    Args:
        api_key: LiveKit API key
        api_secret: LiveKit API secret
        room_name: Name of the room to join
        identity: Unique identifier for the user
        name: Display name for the user
        valid_for_hours: Token validity duration in hours
    
    Returns:
        JWT token string
    """
    token = api.AccessToken(api_key, api_secret)
    token.with_identity(identity)
    token.with_name(name)
    token.with_grants(api.VideoGrants(
        room_join=True,
        room=room_name,
        can_publish=True,
        can_subscribe=True,
        can_publish_data=True,
    ))
    token.with_ttl(timedelta(hours=valid_for_hours))
    
    return token.to_jwt()


def main():
    print("=" * 70)
    print("🎤 LiveKit Token Generator for Voice Chat")
    print("=" * 70)
    print()
    
    # Read credentials from environment
    api_key = os.getenv('LIVEKIT_API_KEY')
    api_secret = os.getenv('LIVEKIT_API_SECRET')
    livekit_url = os.getenv('LIVEKIT_URL', 'wss://your-server.livekit.cloud')
    
    if not api_key:
        print("❌ Error: LIVEKIT_API_KEY environment variable not set")
        print()
        print("Set it with:")
        print("  export LIVEKIT_API_KEY='your-api-key'")
        print("  (or on Windows: set LIVEKIT_API_KEY=your-api-key)")
        sys.exit(1)
    
    if not api_secret:
        print("❌ Error: LIVEKIT_API_SECRET environment variable not set")
        print()
        print("Set it with:")
        print("  export LIVEKIT_API_SECRET='your-api-secret'")
        print("  (or on Windows: set LIVEKIT_API_SECRET=your-api-secret)")
        sys.exit(1)
    
    print("✅ Credentials loaded from environment variables")
    print(f"   API Key: {api_key[:10]}...")
    print(f"   Server URL: {livekit_url}")
    print()
    
    # Token parameters
    room_name = input("Enter room name [farm-voice-assistant]: ").strip() or "farm-voice-assistant"
    identity = input("Enter user identity [farmer-user]: ").strip() or "farmer-user"
    name = input("Enter user display name [Farmer]: ").strip() or "Farmer"
    
    try:
        hours = int(input("Token validity (hours) [24]: ").strip() or "24")
    except ValueError:
        hours = 24
    
    print()
    print("Generating token...")
    
    try:
        token = generate_token(
            api_key=api_key,
            api_secret=api_secret,
            room_name=room_name,
            identity=identity,
            name=name,
            valid_for_hours=hours
        )
        
        print()
        print("=" * 70)
        print("✅ Token generated successfully!")
        print("=" * 70)
        print()
        print("Your LiveKit Token:")
        print("-" * 70)
        print(token)
        print("-" * 70)
        print()
        print("Token Details:")
        print(f"  Room: {room_name}")
        print(f"  Identity: {identity}")
        print(f"  Display Name: {name}")
        print(f"  Valid For: {hours} hours")
        print()
        print("=" * 70)
        print("How to use this token:")
        print("=" * 70)
        print()
        print("1. Export as environment variable:")
        print(f"   export LIVEKIT_TOKEN='{token}'")
        print()
        print("2. Run your Flutter app with all credentials:")
        print()
        print("   flutter run \\")
        print(f"     --dart-define=GEMINI_API_KEY='your-gemini-key' \\")
        print(f"     --dart-define=LIVEKIT_URL='{livekit_url}' \\")
        print(f"     --dart-define=LIVEKIT_TOKEN='{token}'")
        print()
        print("=" * 70)
        print("⚠️  SECURITY NOTES:")
        print("=" * 70)
        print("- This token is valid for", hours, "hours")
        print("- Do NOT commit tokens to Git")
        print("- Do NOT share tokens publicly")
        print("- In production, generate tokens server-side")
        print("- Tokens should be short-lived and user-specific")
        print()
        
    except Exception as e:
        print()
        print(f"❌ Error generating token: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
