

class VoiceChatConfig {
  /// Gemini API configuration
  static const String geminiApiKey = String.fromEnvironment(
    'GEMINI_API_KEY',
    defaultValue: 'AIzaSyCVrl6QD5zJOm8ZBFuxqgMueTlRlQRMbsw',
  );

  /// Gemini model to use (gemini-2.0-flash is recommended for voice)
  static const String geminiModel = 'gemini-2.0-flash';

  /// LiveKit server URL
  /// For LiveKit Cloud: wss://your-project.livekit.cloud
  /// For self-hosted: wss://your-server.com
  static const String livekitUrl = String.fromEnvironment(
    'LIVEKIT_URL',
    defaultValue: 'wss://mabroukas-assistant-ykypiir9.livekit.cloud',
  );

  /// LiveKit API Key (for token generation)
  static const String livekitApiKey = String.fromEnvironment(
    'LIVEKIT_API_KEY',
    defaultValue: 'APItDb5TvWMpVka',
  );

  /// LiveKit API Secret (for token generation)
  static const String livekitApiSecret = String.fromEnvironment(
    'LIVEKIT_API_SECRET',
    defaultValue: 'TgdPbPhF20GB6s3DG1HafOPXMriI5WQ4FQh24UjaOoI',
  );

  /// LiveKit access token
  /// IMPORTANT: In production, tokens should be generated by your backend
  /// For now, tokens will be generated on-demand using API key and secret
  static const String livekitToken = String.fromEnvironment(
    'LIVEKIT_TOKEN',
    defaultValue: '', // Will be generated dynamically
  );

  /// Room name for voice chat
  static const String livekitRoomName = String.fromEnvironment(
    'LIVEKIT_ROOM',
    defaultValue: 'farm-voice-assistant',
  );

  /// Check if configuration is valid
  static bool isConfigured() {
    return geminiApiKey.isNotEmpty &&
           geminiApiKey != 'YOUR_GEMINI_API_KEY_HERE' &&
           livekitUrl.isNotEmpty &&
           livekitUrl != 'wss://your-livekit-server.com' &&
           livekitApiKey.isNotEmpty &&
           livekitApiSecret.isNotEmpty;
  }

  /// Get configuration status message in Arabic
  static String getConfigStatusMessage() {
    if (isConfigured()) {
      return '✅ الإعدادات جاهزة';
    }
    
    final missing = <String>[];
    if (geminiApiKey.isEmpty || geminiApiKey == 'YOUR_GEMINI_API_KEY_HERE') {
      missing.add('Gemini API Key');
    }
    if (livekitUrl.isEmpty || livekitUrl == 'wss://your-livekit-server.com') {
      missing.add('LiveKit URL');
    }
    if (livekitApiKey.isEmpty) {
      missing.add('LiveKit API Key');
    }
    if (livekitApiSecret.isEmpty) {
      missing.add('LiveKit API Secret');
    }
    
    return '⚠️ يرجى تكوين: ${missing.join(', ')}';
  }

  /// System instruction for Gemini (Arabic agricultural assistant)
  static const String geminiSystemInstruction = '''أنت مساعد زراعي ذكي متخصص في المزارع التونسية.
دورك هو مساعدة المزارعين في:
- معرفة حالة النباتات المزروعة
- تقديم نصائح للري والعناية بالنباتات
- الإجابة عن أسئلة حول الزراعة
- توفير معلومات عن المحاصيل والأمراض

قواعد مهمة:
1. استخدم اللغة العربية فقط في جميع الردود
2. كن واضحاً ومباشراً
3. استخدم لغة بسيطة يفهمها المزارعون
4. قدم معلومات عملية ومفيدة
5. كن مشجعاً وإيجابياً
6. إذا لم تكن متأكداً من المعلومة، قل ذلك بوضوح
7. ركز على الزراعة المستدامة والحفاظ على الماء

عند سؤالك عن النباتات، استخدم المعلومات المتاحة من المزرعة.
عند تقديم النصائح، خذ بعين الاعتبار المناخ المتوسطي التونسي.''';
}
