/// Configuration for LiveKit and Gemini voice chat integration
/// 
/// To use this feature, you need to:
/// 1. Get a Gemini API key from https://makersuite.google.com/app/apikey
/// 2. Set up a LiveKit server or use LiveKit Cloud
/// 3. Generate LiveKit tokens for authentication
/// 
/// For production use, store these values securely:
/// - Use environment variables
/// - Use Flutter's secure storage
/// - Use a backend service to generate tokens

class VoiceChatConfig {
  /// Gemini API configuration
  static const String geminiApiKey = String.fromEnvironment(
    'GEMINI_API_KEY',
    defaultValue: 'YOUR_GEMINI_API_KEY_HERE',
  );

  /// Gemini model to use (gemini-2.0-flash is recommended for voice)
  static const String geminiModel = 'gemini-2.0-flash';

  /// LiveKit server URL
  /// For LiveKit Cloud: wss://your-project.livekit.cloud
  /// For self-hosted: wss://your-server.com
  static const String livekitUrl = String.fromEnvironment(
    'LIVEKIT_URL',
    defaultValue: 'wss://your-livekit-server.com',
  );

  /// LiveKit access token
  /// IMPORTANT: In production, tokens should be generated by your backend
  /// Do not hardcode tokens in the app
  static const String livekitToken = String.fromEnvironment(
    'LIVEKIT_TOKEN',
    defaultValue: 'YOUR_LIVEKIT_TOKEN_HERE',
  );

  /// Room name for voice chat
  static const String livekitRoomName = String.fromEnvironment(
    'LIVEKIT_ROOM',
    defaultValue: 'farm-voice-assistant',
  );

  /// Check if configuration is valid
  static bool isConfigured() {
    return geminiApiKey != 'YOUR_GEMINI_API_KEY_HERE' &&
           livekitUrl != 'wss://your-livekit-server.com' &&
           livekitToken != 'YOUR_LIVEKIT_TOKEN_HERE';
  }

  /// Get configuration status message in Arabic
  static String getConfigStatusMessage() {
    if (isConfigured()) {
      return 'الإعدادات جاهزة';
    }
    
    final missing = <String>[];
    if (geminiApiKey == 'YOUR_GEMINI_API_KEY_HERE') {
      missing.add('Gemini API Key');
    }
    if (livekitUrl == 'wss://your-livekit-server.com') {
      missing.add('LiveKit URL');
    }
    if (livekitToken == 'YOUR_LIVEKIT_TOKEN_HERE') {
      missing.add('LiveKit Token');
    }
    
    return 'يرجى تكوين: ${missing.join(', ')}';
  }

  /// System instruction for Gemini (Arabic agricultural assistant)
  static const String geminiSystemInstruction = '''أنت مساعد زراعي ذكي متخصص في المزارع التونسية.
دورك هو مساعدة المزارعين في:
- معرفة حالة النباتات المزروعة
- تقديم نصائح للري والعناية بالنباتات
- الإجابة عن أسئلة حول الزراعة
- توفير معلومات عن المحاصيل والأمراض

قواعد مهمة:
1. استخدم اللغة العربية فقط في جميع الردود
2. كن واضحاً ومباشراً
3. استخدم لغة بسيطة يفهمها المزارعون
4. قدم معلومات عملية ومفيدة
5. كن مشجعاً وإيجابياً
6. إذا لم تكن متأكداً من المعلومة، قل ذلك بوضوح
7. ركز على الزراعة المستدامة والحفاظ على الماء

عند سؤالك عن النباتات، استخدم المعلومات المتاحة من المزرعة.
عند تقديم النصائح، خذ بعين الاعتبار المناخ المتوسطي التونسي.''';
}
